# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 18:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(default=0)),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novel_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('like', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('is_first', models.BooleanField()),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraph_set', to='storyboard.Novel')),
                ('prev_paragraph', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_paragraph_set', to='storyboard.Paragraph')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraph_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
