# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0002_auto_20160712_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
