# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyboard', '0003_paragraph_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='index',
            field=models.IntegerField(default=1),
        ),
    ]
